# Generated by Django 6.0.3 on 2026-03-05 14:51

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('season', models.CharField(help_text='e.g., Summer, Winter, Monsoon', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255)),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('temperature', models.FloatField(help_text='Temperature in Celsius')),
                ('humidity', models.FloatField(help_text='Humidity percentage')),
                ('rainfall', models.FloatField(default=0, help_text='Rainfall in mm')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('farmer', 'Farmer'), ('buyer', 'Buyer'), ('expert', 'Expert'), ('admin', 'Admin')], default='farmer', max_length=10)),
                ('phone', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('region', models.CharField(blank=True, help_text='e.g., Dhaka, Rajshahi, Cumilla', max_length=100, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='api_users', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='api_users', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('response', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='chat_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Land Prep, Seed Planting', max_length=100)),
                ('duration_days', models.IntegerField(help_text='Estimated duration in days')),
                ('optimistic_time', models.IntegerField(help_text='Optimistic duration (O)')),
                ('most_likely_time', models.IntegerField(help_text='Most likely duration (M)')),
                ('pessimistic_time', models.IntegerField(help_text='Pessimistic duration (P)')),
                ('order', models.IntegerField(default=0, help_text='Order in the process')),
                ('dependencies', models.ManyToManyField(blank=True, help_text='Activities that must be completed before this one', to='api.activity')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.crop')),
            ],
            options={
                'ordering': ['crop', 'order'],
            },
        ),
        migrations.CreateModel(
            name='CropRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_type', models.CharField(choices=[('clay', 'Clay'), ('loam', 'Loam'), ('sandy', 'Sandy'), ('silt', 'Silt')], max_length=10)),
                ('season', models.CharField(choices=[('kharif', 'Kharif'), ('rabi', 'Rabi'), ('zaid', 'Zaid')], max_length=10)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('expected_yield', models.DecimalField(decimal_places=2, help_text='Expected yield in tons/acre', max_digits=10)),
                ('tips', models.TextField(blank=True)),
                ('confidence', models.DecimalField(decimal_places=2, default=0.0, help_text='Confidence level 0-1', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommended_crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.crop')),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('symptoms', models.TextField()),
                ('treatment', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='diseases/')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.crop')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_cost', models.DecimalField(decimal_places=2, help_text='Seed cost in BDT', max_digits=10)),
                ('fertilizer_cost', models.DecimalField(decimal_places=2, help_text='Fertilizer cost in BDT', max_digits=10)),
                ('labour_cost', models.DecimalField(decimal_places=2, help_text='Labour cost in BDT', max_digits=10)),
                ('other_cost', models.DecimalField(decimal_places=2, help_text='Other costs in BDT', max_digits=10)),
                ('area', models.DecimalField(decimal_places=2, help_text='Area in acres', max_digits=10)),
                ('expected_yield_per_area', models.DecimalField(decimal_places=2, help_text='Expected yield per area in kg/acre', max_digits=10)),
                ('market_price_per_kg', models.DecimalField(decimal_places=2, help_text='Market price per kg in BDT', max_digits=10)),
                ('actual_yield', models.DecimalField(blank=True, decimal_places=2, help_text='Actual yield in kg', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expected_total_yield', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expected_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expected_profit_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expected_profit_margin', models.DecimalField(blank=True, decimal_places=2, help_text='Expected profit margin in %', max_digits=5, null=True)),
                ('actual_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_profit_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_profit_margin', models.DecimalField(blank=True, decimal_places=2, help_text='Actual profit margin in %', max_digits=5, null=True)),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_calculations', to='api.crop')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_calculations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(help_text='ফসলের নাম', max_length=100)),
                ('market_name', models.CharField(help_text='বাজারের নাম', max_length=100)),
                ('district', models.CharField(help_text='জেলা', max_length=100)),
                ('price_per_kg', models.DecimalField(decimal_places=2, help_text='প্রতি kg এর দাম (BDT)', max_digits=10)),
                ('date', models.DateField(auto_now_add=True, help_text='তারিখ')),
                ('source', models.CharField(default='manual', help_text='উৎস (manual, govt_api)', max_length=50)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_updated_prices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('notification_type', models.CharField(choices=[('admin_reply', 'Admin Reply'), ('weather_alert', 'Weather Alert'), ('price_update', 'Price Update'), ('system_reminder', 'System Reminder')], default='system_reminder', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the post is currently active/relevant')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.post')),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='problems/')),
                ('video', models.FileField(blank=True, null=True, upload_to='problem_videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tracking_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('ai_processing', 'AI Processing'), ('ai_completed', 'AI Completed'), ('expert_review', 'Expert Review'), ('expert_completed', 'Expert Completed'), ('resolved', 'Resolved')], default='submitted', max_length=20)),
                ('ai_solution', models.TextField(blank=True, null=True)),
                ('expert_solution', models.TextField(blank=True, null=True)),
                ('solution_date', models.DateTimeField(blank=True, null=True)),
                ('crop_type', models.CharField(blank=True, max_length=100, null=True)),
                ('problem_type', models.CharField(blank=True, choices=[('পোকা', 'পোকা'), ('রোগ', 'রোগ'), ('সারের অভাব', 'সারের অভাব'), ('আবহাওয়া', 'আবহাওয়া'), ('মাটি', 'মাটি'), ('অন্যান্য', 'অন্যান্য')], max_length=100, null=True)),
                ('start_date', models.CharField(blank=True, choices=[('আজ', 'আজ'), ('গতকাল', 'গতকাল'), ('২-৩ দিন আগে', '২-৩ দিন আগে'), ('১ সপ্তাহ আগে', '১ সপ্তাহ আগে'), ('২ সপ্তাহ আগে', '২ সপ্তাহ আগে'), ('১ মাস আগে', '১ মাস আগে'), ('আরও আগে', 'আরও আগে')], max_length=50, null=True)),
                ('severity_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('assigned_expert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_problems', to=settings.AUTH_USER_MODEL)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_analysis', models.TextField(blank=True, null=True)),
                ('expert_analysis', models.TextField(blank=True, null=True)),
                ('recommended_treatment', models.TextField(blank=True, null=True)),
                ('preventive_measures', models.TextField(blank=True, null=True)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0.0, help_text='AI confidence score 0-1', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solution', to='api.problem')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.problem')),
            ],
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_critical', models.BooleanField(default=False)),
                ('weather_delay_days', models.IntegerField(default=0)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.activity')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.crop')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timelines', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_percentage', models.IntegerField(default=0, help_text='0-100')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('timeline', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='api.timeline')),
            ],
        ),
    ]
