# Generated by Django 5.2 on 2025-10-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('season', models.CharField(help_text='e.g., Summer, Winter, Monsoon', max_length=50)),
            ],
        ),
    ]
