# Generated by Django 5.2 on 2025-10-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_weatherdata_user_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates if the post is currently active/relevant'),
        ),
    ]
