# Generated by Django 5.2 on 2025-10-24 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_post_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Land Prep, Seed Planting', max_length=100)),
                ('duration_days', models.IntegerField(help_text='Estimated duration in days')),
                ('optimistic_time', models.IntegerField(help_text='Optimistic duration (O)')),
                ('most_likely_time', models.IntegerField(help_text='Most likely duration (M)')),
                ('pessimistic_time', models.IntegerField(help_text='Pessimistic duration (P)')),
                ('order', models.IntegerField(default=0, help_text='Order in the process')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.crop')),
                ('dependencies', models.ManyToManyField(blank=True, help_text='Activities that must be completed before this one', to='api.activity')),
            ],
            options={
                'ordering': ['crop', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_critical', models.BooleanField(default=False)),
                ('weather_delay_days', models.IntegerField(default=0)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.activity')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.crop')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timelines', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_percentage', models.IntegerField(default=0, help_text='0-100')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('timeline', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='api.timeline')),
            ],
        ),
    ]
