# Generated by Django 5.2 on 2025-10-30 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_activity_timeline_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(help_text='ফসলের নাম (ধান, গম, পেঁয়াজ, আলু...)', max_length=100)),
                ('market_name', models.CharField(help_text="বাজারের নাম (যেমন 'Bogura Market')", max_length=100)),
                ('district', models.CharField(help_text='জেলার নাম', max_length=100)),
                ('price_per_kg', models.DecimalField(decimal_places=2, help_text='প্রতি কেজির দাম (BDT)', max_digits=10)),
                ('date', models.DateField(help_text='দাম update হওয়ার তারিখ')),
                ('source', models.CharField(choices=[('Govt API', 'Govt API'), ('Manual Entry', 'Manual Entry')], default='Manual Entry', max_length=50)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_prices', to='api.user')),
            ],
            options={
                'ordering': ['-date', 'crop_name', 'market_name'],
                'unique_together': {('crop_name', 'market_name', 'district', 'date')},
            },
        ),
    ]
