# Generated by Django 5.2 on 2025-11-01 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_marketprice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marketprice',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='marketprice',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='marketprice',
            name='crop_name',
            field=models.CharField(help_text='ফসলের নাম', max_length=100),
        ),
        migrations.AlterField(
            model_name='marketprice',
            name='date',
            field=models.DateField(auto_now_add=True, help_text='তারিখ'),
        ),
        migrations.AlterField(
            model_name='marketprice',
            name='district',
            field=models.CharField(help_text='জেলা', max_length=100),
        ),
        migrations.AlterField(
            model_name='marketprice',
            name='market_name',
            field=models.CharField(help_text='বাজারের নাম', max_length=100),
        ),
        migrations.AlterField(
            model_name='marketprice',
            name='price_per_kg',
            field=models.DecimalField(decimal_places=2, help_text='প্রতি kg এর দাম (BDT)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='marketprice',
            name='source',
            field=models.CharField(default='manual', help_text='উৎস (manual, govt_api)', max_length=50),
        ),
        migrations.AlterField(
            model_name='marketprice',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_updated_prices', to=settings.AUTH_USER_MODEL),
        ),
    ]
