# Generated by Django 5.2 on 2025-11-01 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_marketprice_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_cost', models.DecimalField(decimal_places=2, help_text='Seed cost in BDT', max_digits=10)),
                ('fertilizer_cost', models.DecimalField(decimal_places=2, help_text='Fertilizer cost in BDT', max_digits=10)),
                ('labour_cost', models.DecimalField(decimal_places=2, help_text='Labour cost in BDT', max_digits=10)),
                ('other_cost', models.DecimalField(decimal_places=2, help_text='Other costs in BDT', max_digits=10)),
                ('area', models.DecimalField(decimal_places=2, help_text='Area in acres', max_digits=10)),
                ('expected_yield_per_area', models.DecimalField(decimal_places=2, help_text='Expected yield per area in kg/acre', max_digits=10)),
                ('market_price_per_kg', models.DecimalField(decimal_places=2, help_text='Market price per kg in BDT', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_yield', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('profit_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('profit_margin', models.DecimalField(blank=True, decimal_places=2, help_text='Profit margin in %', max_digits=5, null=True)),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_calculations', to='api.crop')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_calculations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
