# Generated by Django 5.2 on 2025-11-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_expensecalculation_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecalculation',
            name='actual_profit_loss',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual profit/loss in BDT', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='expensecalculation',
            name='actual_profit_margin',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual profit margin in %', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='expensecalculation',
            name='actual_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual revenue in BDT', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='expensecalculation',
            name='actual_yield',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual yield in kg', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='expensecalculation',
            name='expected_profit_loss',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Expected profit/loss in BDT', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='expensecalculation',
            name='expected_profit_margin',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Expected profit margin in %', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='expensecalculation',
            name='expected_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Expected revenue in BDT', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='expensecalculation',
            name='expected_total_yield',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Expected total yield in kg', max_digits=10, null=True),
        ),
        migrations.RenameField(
            model_name='expensecalculation',
            old_name='profit_loss',
            new_name='actual_profit_loss',
        ),
        migrations.RenameField(
            model_name='expensecalculation',
            old_name='profit_margin',
            new_name='actual_profit_margin',
        ),
        migrations.RenameField(
            model_name='expensecalculation',
            old_name='revenue',
            new_name='actual_revenue',
        ),
        migrations.RenameField(
            model_name='expensecalculation',
            old_name='total_yield',
            new_name='expected_total_yield',
        ),
    ]
