# Generated by Django 5.2 on 2025-11-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_update_expense_calculation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensecalculation',
            name='actual_profit_margin',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual profit margin in %', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='expensecalculation',
            name='expected_profit_loss',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='expensecalculation',
            name='expected_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
