# Generated by Django 5.2 on 2025-11-01 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_notification_notification_type_notification_priority_and_more'),
    ]

    operations = [
    ]
