# Generated by Django 5.2 on 2025-11-01 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_add_crop_recommendation_and_notification_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_type', models.CharField(choices=[('clay', 'Clay'), ('loam', 'Loam'), ('sandy', 'Sandy'), ('silt', 'Silt')], max_length=10)),
                ('season', models.CharField(choices=[('kharif', 'Kharif'), ('rabi', 'Rabi'), ('zaid', 'Zaid')], max_length=10)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('expected_yield', models.DecimalField(decimal_places=2, help_text='Expected yield in tons/acre', max_digits=10)),
                ('tips', models.TextField(blank=True)),
                ('confidence', models.DecimalField(decimal_places=2, default=0.0, help_text='Confidence level 0-1', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommended_crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.crop')),
            ],
        ),
    ]
