# Generated by Django 5.2 on 2025-11-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_create_crop_recommendation_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='croprecommendation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('buyer', 'Buyer'), ('expert', 'Expert'), ('admin', 'Admin')], default='farmer', max_length=10),
        ),
    ]
