# Generated by Django 5.2 on 2025-11-05 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_disease'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='ai_solution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='assigned_expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_problems', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='problem',
            name='crop_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='expert_solution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='severity_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='problem',
            name='solution_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('ai_processing', 'AI Processing'), ('ai_completed', 'AI Completed'), ('expert_review', 'Expert Review'), ('expert_completed', 'Expert Completed'), ('resolved', 'Resolved')], default='submitted', max_length=20),
        ),
        migrations.AddField(
            model_name='problem',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='problem_videos/'),
        ),
        migrations.CreateModel(
            name='ProblemSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_analysis', models.TextField(blank=True, null=True)),
                ('expert_analysis', models.TextField(blank=True, null=True)),
                ('recommended_treatment', models.TextField(blank=True, null=True)),
                ('preventive_measures', models.TextField(blank=True, null=True)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0.0, help_text='AI confidence score 0-1', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solution', to='api.problem')),
            ],
        ),
    ]
