# Generated by Django 5.2 on 2025-11-05 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_problem_ai_solution_problem_assigned_expert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='problem_type',
            field=models.CharField(blank=True, choices=[('পোকা', 'পোকা'), ('রোগ', 'রোগ'), ('সারের অভাব', 'সারের অভাব'), ('আবহাওয়া', 'আবহাওয়া'), ('মাটি', 'মাটি'), ('অন্যান্য', 'অন্যান্য')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='start_date',
            field=models.CharField(blank=True, choices=[('আজ', 'আজ'), ('গতকাল', 'গতকাল'), ('২-৩ দিন আগে', '২-৩ দিন আগে'), ('১ সপ্তাহ আগে', '১ সপ্তাহ আগে'), ('২ সপ্তাহ আগে', '২ সপ্তাহ আগে'), ('১ মাস আগে', '১ মাস আগে'), ('আরও আগে', 'আরও আগে')], max_length=50, null=True),
        ),
    ]
