# Generated by Django 5.1.3 on 2025-11-27 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_problem_problem_type_problem_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensecalculation',
            name='actual_profit_loss',
        ),
        migrations.RemoveField(
            model_name='expensecalculation',
            name='actual_profit_margin',
        ),
        migrations.RemoveField(
            model_name='expensecalculation',
            name='actual_revenue',
        ),
        migrations.RemoveField(
            model_name='expensecalculation',
            name='actual_yield',
        ),
    ]
