# Generated by Django 5.1.3 on 2025-11-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_expensecalculation_actual_profit_loss_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecalculation',
            name='actual_profit_loss',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='expensecalculation',
            name='actual_profit_margin',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual profit margin in %', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='expensecalculation',
            name='actual_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='expensecalculation',
            name='actual_yield',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual yield in kg', max_digits=10, null=True),
        ),
    ]
