from django.urls import path
from . import views
from . import admin_views

urlpatterns = [
    path('', views.api_root, name='api_root'),
    path('auth/send-otp/', views.send_otp, name='send_otp'),
    path('auth/verify-otp/', views.verify_otp, name='verify_otp'),
    path('auth/reset-password/', views.reset_password, name='reset_password'),
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('posts/', views.posts_list, name='posts_list'),
    path('posts/search/', views.search_posts, name='search_posts'),
    path('posts/create/', views.create_post, name='create_post'),
    path('posts/<int:post_id>/comment/', views.create_comment, name='create_comment'),
    path('problems/', views.problems_list, name='problems_list'),
    path('problems/create/', views.create_problem, name='create_problem'),
    path('problems/<int:problem_id>/reply/', views.create_reply, name='create_reply'),
    path('stats/', views.stats, name='stats'),
    path('crops/', views.crops_list, name='crops_list'),
    path('crops/<int:crop_id>/description/', views.crop_description, name='crop_description'),
    path('crops/<int:crop_id>/progress/', views.crop_progress, name='crop_progress'),
    path('weather/<int:crop_id>/', views.weather_advice, name='weather_advice'),
    path('chat/history/', views.chat_history, name='chat_history'),
    path('chat/', views.chat_with_ai, name='chat_with_ai'),
    path('crop-health/', views.crop_health, name='crop_health'),
    path('problem-trends/', views.problem_trends, name='problem_trends'),
    path('weather-trends/', views.weather_trends, name='weather_trends'),
    path('advice-insights/', views.advice_insights, name='advice_insights'),
    path('region-problems/', views.region_problems, name='region_problems'),
    path('top-crops/', views.top_crops, name='top_crops'),
    path('activity-summary/', views.activity_summary, name='activity_summary'),
    path('current-weather/', views.current_weather, name='current_weather'),
    path('current-weather-live/', views.current_weather_live, name='current_weather_live'),
    path('crops/<int:crop_id>/activities/', views.activities_list, name='activities_list'),
    path('farmer-timeline/', views.farmer_timeline, name='farmer_timeline'),
    path('farmer-dashboard-data/', views.dashboard_stats, name='dashboard_stats'),
    path('create-timeline/', views.create_timeline, name='create_timeline'),
    path('update-progress/<int:timeline_id>/', views.update_progress, name='update_progress'),
    path('pert-analysis/<int:crop_id>/', views.pert_analysis, name='pert_analysis'),
    path('admin-analytics/', views.admin_analytics, name='admin_analytics'),
    path('market-prices/create/', views.create_market_price, name='create_market_price'),
    path('market-prices/', views.market_prices, name='market_prices'),
    path('market-prices/auto-refresh/', views.auto_refresh_prices, name='auto_refresh_prices'),
    path('market-prices/govt-api/', views.govt_api_prices, name='govt_api_prices'),
    path('market-prices/ai-suggestions/', views.ai_price_suggestions, name='ai_price_suggestions'),
    path('expense-calculations/', views.expense_calculations_list, name='expense_calculations_list'),
    path('expense-calculations/<int:calculation_id>/', views.expense_calculation_detail, name='expense_calculation_detail'),
    path('crop-recommendations/', views.crop_recommendations, name='crop_recommendations'),
    path('recommend-crop/', views.recommend_crop, name='recommend_crop'),
    path('notifications/', views.notifications_list, name='notifications_list'),
    path('notifications/<int:notification_id>/mark-read/', views.mark_notification_read, name='mark_notification_read'),
    path('notifications/create/', views.create_notification, name='create_notification'),
    path('welcome/', views.welcome, name='welcome'),
    path('hello/', views.hello, name='hello'),
    # Agri-Doctor URLs
    path('problems/<int:problem_id>/ai-analyze/', views.ai_analyze_problem, name='ai_analyze_problem'),
    path('problems/<int:problem_id>/expert-review/', views.expert_review_problem, name='expert_review_problem'),
    path('problems/<int:problem_id>/results/', views.farmer_problem_results, name='farmer_problem_results'),
    path('expert/pending-problems/', views.expert_pending_problems, name='expert_pending_problems'),
    path('expert/problems/', views.expert_pending_problems, name='expert_pending_problems_alias'),
    path('expert/knowledge-base/', views.expert_knowledge_base, name='expert_knowledge_base'),
    path('expert/reviews/', views.expert_reviews, name='expert_reviews'),

    # Market and Buyer URLs
    path('market/products/', views.market_products, name='market_products'),
    path('market/', views.market_list, name='market_list'),
    path('market/order/', views.create_order, name='create_order'),
    path('market/delete/<int:pk>/', views.delete_market_post, name='delete_market_post'),
    path('market/buy/<int:item_id>/', views.buy_item, name='buy_item'),
    path('market/new/', views.create_market_post, name='create_market_post'),
    path('buyer/orders/', views.buyer_orders, name='buyer_orders'),
    path('farmers/profiles/', views.farmer_profiles, name='farmer_profiles'),
    path('market/price-analysis/', views.market_price_analysis, name='market_price_analysis'),
    path('buyer/inventory/', views.buyer_inventory, name='buyer_inventory'),
    path('farmer/orders/', views.farmer_orders, name='farmer_orders'),
    path('farmer/orders/<int:order_id>/update-status/', views.update_order_status, name='update_order_status'),

    # Admin Panel URLs (New)
    path('admin/users/', admin_views.admin_users, name='admin_users'),
    path('admin/users/<int:pk>/', admin_views.update_user_status, name='update_user_status'),
    path('admin/products/', admin_views.admin_products, name='admin_products'),
    path('admin/transactions/', admin_views.admin_transactions, name='admin_transactions'),
    path('admin/content/', admin_views.admin_content, name='admin_content'),
    path('admin/content/<int:pk>/', admin_views.admin_content, name='admin_content_delete'),
    path('admin/reports/', admin_views.admin_reports, name='admin_reports'),
]
