# Generated by Django 6.0.3 on 2026-03-05 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(help_text='ফসলের নাম', max_length=100)),
                ('market_name', models.CharField(help_text='বাজারের নাম', max_length=100)),
                ('district', models.CharField(help_text='জেলা', max_length=100)),
                ('price_per_kg', models.DecimalField(decimal_places=2, help_text='প্রতি kg এর দাম (BDT)', max_digits=10)),
                ('date', models.DateField(auto_now_add=True, help_text='তারিখ')),
                ('source', models.CharField(default='manual', help_text='উৎস (manual, govt_api)', max_length=50)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_prices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(help_text='ফসলের নাম (ধান, গম, পেঁয়াজ, আলু...)', max_length=100)),
                ('quantity', models.FloatField(help_text='পরিমাণ (kg বা ton)')),
                ('price', models.DecimalField(decimal_places=2, help_text='প্রতি kg এর দাম (BDT)', max_digits=10)),
                ('location', models.CharField(help_text='বাজার/এলাকা', max_length=100)),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold')], default='available', max_length=10)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_posts', to=settings.AUTH_USER_MODEL)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(help_text='Quantity ordered (kg)')),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total calculated price', max_digits=12)),
                ('buyer_location', models.CharField(help_text='Delivery location', max_length=255)),
                ('buyer_phone', models.CharField(help_text='Contact number', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('product_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='market.productpost')),
            ],
        ),
    ]
